### ISSUE TITLE
Send out to 50 rep tracker clients

### ISSUE THREAD

**Issue by officite** [ahuensch/officite#110]
Can you send the below rep tracker email out to 50 rep tracker clients who have had the program 4-6 months? 

https://na13.salesforce.com/00Xa0000001jNdr?setupid=EmailTemplates

Wasn't sure what the easiest way to do this. email lindsey if you have questions.

**Comment by ahuensch** [comment]
Sent from reptracker@officite.com?

On Mon, Jul 27, 2015 at 2:38 PM, officite <notifications@github.com> wrote:

> Can you send the below rep tracker email out to 50 rep tracker clients who
> have had the program 4-6 months?
>
> https://na13.salesforce.com/00Xa0000001jNdr?setupid=EmailTemplates
>
> Wasn't sure what the easiest way to do this. email lindsey if you have
> questions.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ahuensch/officite/issues/110>.
>



-- 
*Anna Huensch*
1546 North LaSalle, Chicago, IL 60610
t *630.639.1960*

**Comment by officite** [comment]
Yes please

**Comment by ahuensch** [comment]
Email has been sent to the primary contacts on 50 active assets sold January 2015 / February 2015. Completed activity logged on the contact record.  Let me know if you need anything else. 

Cheers, 
Anna
