### ISSUE TITLE
Revise Territory Assignments

### ISSUE THREAD

**Issue by officite** [ahuensch/officite#125]
For you 3 I am opening up the ability to sell ancillary products for dental and medical in select states.  These leads and accounts will be transferred over to your name once I can get Anna to do this.  I need to stress that our main action is to sell websites first but given the ability to sell some ancillary products will help with your income.  If Andrea and I feel that we are not getting the same website effort as we are accustomed to then we may need to go back to the website only territories

See your ancillary assignment below and please keep us informed of success stories

1. Sula = Dental in Michigan and Illinois
2. Erica - Dental Virginia, North Carolina, South Carolina
3. Ryan - Medical Texas and California

In addition to these states we need to put rules in place so you are not poaching leads that currently Paul and Bob are working on.  With that said if either rep has activity on an account (even in your territory) for 3 months then you cannot touch it.  If you get a call or lead that falls under this parameter then it needs to go to them

**This is also fluid and could change based on new ancillary reps that we have coming into the company

**Comment by ahuensch** [comment]
Updated Lead Assignment rules / Lead Workflows / Account Workflows to reflect the new territory assignments.  Updated existing Lead / Customer Account records
