### ISSUE TITLE
Domain Transfer Case Notification

### ISSUE THREAD

**Issue by officite** [ahuensch/officite#126]
Generate a popup (a la shared Sesame customer) for the account if there is a domain transfer case pending so CS is aware that it is a pending issue that needs to be addressed. -TF

**Comment by officite** [comment]
"Domain Transfer Case open, please check details to see if anything else is needed from customer."

**Comment by ahuensch** [comment]
Alert Message added for accounts with domain record in the status 'transfer'.  Alert Message is erased when the domain is updated to the status 'resolves standard'

**Comment by officite** [comment]
Can we have cancelled cases filtered out of this as well? So only if a case is open? See: https://na13.salesforce.com/500a000000w3Nha as an example. Thanks -TF

**Comment by ahuensch** [comment]
The domain transfer notification has been updated to erase when the domain is flipped to inactive.  Existing records have been updated.
