### ISSUE TITLE
Revise territory assignments effective July 1st 2015

### ISSUE THREAD

**Issue by officite** [ahuensch/officite#16]
Anna - Tom is moving the territories around on July 1st.  More to come, but I wanted to put this on the radar.

**Comment by ahuensch** [comment]
Has the new territory plan been finalized?

**Comment by officite** [comment]
Tom is still working on it.  Should have something completed by today.



Thanks,



Fred Brown



*From:* Anna Huensch [mailto:notifications@github.com]
*Sent:* Friday, June 12, 2015 8:52 AM
*To:* ahuensch/officite
*Cc:* officite
*Subject:* Re: [officite] Territory Alignment - effective July 1 (#16)



Has the new territory plan been finalized?

—
Reply to this email directly or view it on GitHub
<https://github.com/ahuensch/officite/issues/16#issuecomment-111499502>.

**Comment by officite** [comment]
Fred, please pass along to Anna.



Adam Barnett will get all Dental and Peds in the following states

ID, MT, UT, AZ, WY, CO, NM, TX, OK, KS, MO, NE, SD, ND



Jim Stanley - Will keep his current dental on the east coast and acquire from Erica CT, DE, and RI in Dental

Jim Stanley - Will also acquire from Sula all of his Podiatry which consists of:
MI, IN, KY, TN, MS, AL, GA, FL, SC, NC, VA, WV, OH

Gregg McCambell
Will acquire Dental and Peds in OR only in addition to keeping his current territory

Also ask when Anna needs holdbacks by?  I assume sometime the last week of the month

Tom



Tom Sredl  | Officite | Vice President, Sales
3010 Highland Parkway, Ste. 625, Downers Grove, IL 60515
t 630.230.2314 | f 630.230.2301 | m 224.315.7781

**Comment by ahuensch** [comment]
Okay, great!

Just to confirm  -
Adam Barnett will be a new business rep, correct?
The effective date of this change is 7/1/2015?

Holdbacks are due on 6/30/2015 by 3PM.  I will provide a specific template
for reps to fill out to request a holdback on a lead or account.

Cheers,
Anna

On Fri, Jun 12, 2015 at 1:42 PM, officite <notifications@github.com> wrote:

> Fred, please pass along to Anna.
>
> Adam Barnett will get all Dental and Peds in the following states
>
> ID, MT, UT, AZ, WY, CO, NM, TX, OK, KS, MO, NE, SD, ND
>
> Jim Stanley - Will keep his current dental on the east coast and acquire
> from Erica CT, DE, and RI in Dental
>
> Jim Stanley - Will also acquire from Sula all of his Podiatry which
> consists of:
> MI, IN, KY, TN, MS, AL, GA, FL, SC, NC, VA, WV, OH
>
> Gregg McCambell
> Will acquire Dental and Peds in OR only in addition to keeping his current
> territory
>
> Also ask when Anna needs holdbacks by? I assume sometime the last week of
> the month
>
> Tom
>
> Tom Sredl | Officite | Vice President, Sales
> 3010 Highland Parkway, Ste. 625, Downers Grove, IL 60515
> t 630.230.2314 | f 630.230.2301 | m 224.315.7781
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ahuensch/officite/issues/16#issuecomment-111585864>.
>



-- 
*Anna Huensch*
1546 North LaSalle, Chicago, IL 60610
t *630.639.1960* |  f *866.724.9913*

**Comment by officite** [comment]
Awesome! 
Correct - Adam doesn't know he is moving yet, but the change will go into effect July 1.  I'll have Jim allocate a license for him so he is all set up.

**Comment by officite** [comment]
Adam is now aware of the change and I believe Jim got him a license today.

**Comment by ahuensch** [comment]
I do not see an active license for Adam in the system.  We had another gentleman by the name of Adam Barnett in the CS department back in 2013.   It kind of looks like Jim started to modify it to be for Adam...but I don't think that that is good practice.  We should setup a new license for Adam with a new alias. 

(I'm not crazy these are two different people right?)

If you agree a new license is required...please provide the following information for Adam

First Name
Middle Name
Last Name
Email
Title
Department
Work Phone
Does he require any special Salesforce permissions? i.e. access to queues or custom objects outside of the sales flow

**Comment by officite** [comment]
Adam Barnett is the same guy - he used to work for Officite in 2013 prior to going to Baystone - same permissions as the other WPAs.

Also - Tom is making further tweaks to his plan - more to come later today or tomorrow.

**Comment by ahuensch** [comment]
Please be sure to have the revisions by end of day tomorrow.  I will need to have these changes staged and ready to deploy this weekend. If we're to go-live Tuesday  evening .

**Comment by officite** [comment]
Pulling it together now.

**Comment by ahuensch** [comment]
Confirmed territory model with Sredl
Identified holdback accounts/leads
Updated Lead Assignment Rules
Updated Lead Workflow Rules
Updated Account Workflow Rules
Test important in Sandbox of leads to audit lead assignment rules
Built and Validated change set for 7/1/2015 changes in Production
Emailed Lisa to determine appropriate timing for executing changes because of EOM

**Comment by ahuensch** [comment]
Territory revisions are live. Let me know if there is anything else I can do to assist.
