### ISSUE TITLE
Update blog management report to exclude cancelled assets

### ISSUE THREAD

**Issue by officite** [ahuensch/officite#17]
For the blog management report in salesforce, Brad and I were wondering if it can mirror the SEO report in that when a client cancels, the action task for them permanently falls off the report.  Conversely, when a client starts the SEO program, can they automatically show on the report? 

Currently, Brad has to manually add/remove clients from the report. See Lindsey if you have any questions.

**Comment by ahuensch** [comment]
Blog Posts Due This Month
https://na13.salesforce.com/00Oa0000008nG1V

Has been updated to only include active assets.  As customers cancel blog services, tasks will fall off of the report accordingly. 

New Blog clients will show on the report after Brad has clicked the "Start Program" button on the asset. 

Let me know if you have any additional questions or concerns. 

Cheers, 
Anna
