### ISSUE TITLE
Add the ability to track the onboarding specialist assigned to an account

### ISSUE THREAD

**Issue by officite** [ahuensch/officite#19]
Right now Diane is tracking all of her onboarding clients using Outlook.  I'm looking for a way to create a status for those clients that are in onboarding.  One thing to note, we will soon have multiple onboarding CS reps so we will need a way to assign onboarding clients to an individual.

**Comment by ahuensch** [comment]
What if we start with adding a field to the account to store the assigned onboarding specialists.  With this we can deduce, which accounts are going through the onboarding process with the presence or absence of an onboarding specialist.  Additionally, this will set the groundwork for creating reports and view that filter results by the user assigned to the account. Let me know what you think and I can setup that new field.

**Comment by officite** [comment]
I like this idea Anna - let's do it.

**Comment by ahuensch** [comment]
Added custom field to the account - account.onboarding_specialist__c
Added section to the account page layout - 'Onboarding Details
