### ISSUE TITLE
Provide a customer list of prime Sesame candidates

### ISSUE THREAD

**Issue by officite** [ahuensch/officite#20]
Anna - we are going to be giving Sesame another 50 customers to sell to.  Can you pull a list of 100 Officite clients for me to review who have the most Officite products (highest recurring).

**Comment by ahuensch** [comment]
Attached is a list of the top 100 average monthly clients that:

- are not existing Sesame leads
- market = dental
- type = customer
- are not existing Appointment Reminder clients

Let me know if there is anything else I can do to assist.

Cheers,
Anna

On Mon, Jun 15, 2015 at 9:34 AM, officite <notifications@github.com> wrote:

> Anna - we are going to be giving Sesame another 50 customers to sell to.
> Can you pull a list of 100 Officite clients for me to review who have the
> most Officite products (highest recurring).
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ahuensch/officite/issues/20>.
>



-- 
*Anna Huensch*
1546 North LaSalle, Chicago, IL 60610
t *630.639.1960* |  f *866.724.9913*
