### ISSUE TITLE
Provide contact information for a Portal 2.0 Migration notification to current clients of Portal 1.0

### ISSUE THREAD

**Issue by officite** [ahuensch/officite#21]
Hi Anna,

I would like to send an email communication to the portal 1 clients informing them of the upcoming migration starting this Wednesday, June 17th.  It makes sense to do this in batches, but I am not sure of how many we will need to do.  Would you be able to pull an email list of all portal 1 clients?

Thank you!

Patti

**Comment by ahuensch** [comment]
Yes, I could pull a contact list from Salesforce; however, I hesitate to rely on the Salesforce data to determine if a client is in portal 1 or portal 2.  Have you explored getting a list of website IDs from Sean Graham of websites still in Portal 1?  That would be more accurate and with it I could either update the salesforce data OR join the website IDs with Salesforce contact information to provide a list for reaching out.

**Comment by officite** [comment]
Anna - great point - Patti submitted this today so I'll need to touch base with her tomorrow.  Based on our previous experience I 100% agree with you on this that we should see what we can get from portal.

**Comment by officite** [comment]
Hi Anna,

I just sent you the list from Sean to your gmail account. 

Thanks!

Patti
