### ISSUE TITLE
Tasks Assigned to Wrong WPA

### ISSUE THREAD

**Issue by officite** [ahuensch/officite#24]
Hi Fred, I have been noticing that many open tasks for leads and current clients are assigned to the wrong person. We might need to double check this for both leads and accounts. I have included four examples below. With the constant changing of the territories, I think these accounts/leads have fallen through the cracks. Thanks in advanced for your help!

Ex: Account is assigned to Vanessa Vitagliano, but the open task is assigned to Bob Gavigan: https://na13.salesforce.com/001a000001A3WWa

Ex. Account is assigned to Jim Stanley, but the open task is assigned to Dale Gardner:
https://na13.salesforce.com/001a000001BQ1L4

Ex. Account is assigned to Jim Stanley, but the open task is assigned to Gregg McCampbell: https://na13.salesforce.com/001a000001BQUcg

Ex. Account is assigned to Erica Pense, but the open task is assigned to Gregg McCampbell.

Thanks,
- Vanessa

**Comment by ahuensch** [comment]
Updated Assignee on tasks related to accounts and leads where the existing owner had the role Business Development & Sales Rep and differed from Account Owner or Lead Owner.  ~150 records were updated out of ~3000 open tasks.
