### ISSUE TITLE
Search Specialist Reports

### ISSUE THREAD

**Issue by officite** [ahuensch/officite#26]
Anna - now that we have SEO Specialists with assigned accounts I want to get some regular reporting around number of active clients by SEO Specialist and also churn associated with those clients.  Any thoughts as to what kind of report would make sense here?

**Comment by ahuensch** [comment]
Couple of questions:

What the high level purpose for the visibility? Equality of distribution of work? Performance? 

What time period do you want to look at those metrics?

Would you prefer a dashboard? Recurring Report emailed to you? Report?

For active campaigns: 
Just net counts? Do you need or want to see product types, age, or recurring value?

For cancellations:
Just net counts? Do you need or want to see cancellation types or reasons?

Additionally, can you review the existing Search Dashboards and let me know if there are any I can archive. 

Cheers,
Anna

**Comment by officite** [comment]
I'll review the search dashboards later today and let you know what we can archive.  I think I am looking for both a dashboard and report.  At a high level I want to be able to look at each rep on a monthly basis and have a sense for how many of their clients are canceling.  In addition I want visibility into how the accounts are being separated so that as new clients come on Lindsey has a better idea of who to assign the new accounts to.  So it is both a performance and work equality review.  Product Type would be cool, but isn't essential.  Just net counts on cancels.  Perhaps on the dashboard a net cancels this month by rep.  At the end of the month I will want to run a report like the SEO Cancels report currently, which has most of what I want, just doesn't have who the Search Specialist is
.

**Comment by officite** [comment]
The only three dashboards that I currently use are: 
Search Team Member Performance Dashboard
Home Page: Search Specialist Dashboard 
SEO Dashboard

In regards to individual reports, I only use: 
calls by search team
emails by search team

You can remove the rest:
SEO Assets with no SEO start date
Brite Local Cleanup Report
SEO Campaigns w/ mobile
SEO Campaigns w/out  mobile
SEO Expired May-July '13
SEO Retention by Month (MockUp) - not sure if this is something currently being worked on?
All the "SEO Renewal" reports - I think these are from last year, but again, not sure if this is something currently being worked on (probably not, looks like Tom Brown created them).

**Comment by ahuensch** [comment]
Retired SEO reports and dashboards. 

Took a stab at a new SEO Dashboard: 

Search Specialist Shanpshot
https://na13.salesforce.com/01Za0000000fgcD

Feel free to open subsequent issues to modify or add modules.
