### ISSUE TITLE
Add Dear Doctor TV as an Asset in SF

### ISSUE THREAD

**Issue by officite** [ahuensch/officite#27]

**Comment by officite** [comment]
I will pull together pricing and add to this chain.

**Comment by ahuensch** [comment]
Is this sold as a pair of products (i.e. a setup/recurring)?
Asset Feature Type?
Product Name?
Does it require a setup case?
Does it require a case on cancellation?
What does Dear Doctor require to as a product name?
What is the royalty rate due?
What is the retail pricing?


On Thu, Jun 18, 2015 at 1:50 PM, officite <notifications@github.com> wrote:

> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ahuensch/officite/issues/27>.
>



-- 
*Anna Huensch*
1546 North LaSalle, Chicago, IL 60610
t *630.639.1960* |  f *866.724.9913*

**Comment by officite** [comment]
I'll get you answers to the above later today or tomorrow Anna.

**Comment by officite** [comment]
Still waiting for finalized pricing from Don.

Product Name? Dear Doctor TV
Does it require a setup case? Yes.
Does it require a case on cancellation? Yes.  We will need to let Dear Doctor TV know.
Asset Feature Type?  Not sure where it makes the most sense – this is very different than our other products and we are acting in the role of a reseller.

**Comment by ahuensch** [comment]
How should we notify Dear Doctor TV? Is there an email address we can automate an alert to? If so, what is the address? What content should we include? 

Asset Feature Type - Maybe grouped in with Patient Education? You'll have to ask Debbie it is mostly her call.
