### ISSUE TITLE
Add new directory listing to follow HotFrog in sequence - 'SuperPages'

### ISSUE THREAD

**Issue by ahuensch** [ahuensch/officite#32]

**Comment by officite** [comment]
Let's go with Superpages initially. If you can create the tasks, I'll do some beta testing.
Thanks -TF

**Comment by ahuensch** [comment]
--Superpages tasks assigned to ~950 open tasks

--To Do List (with Local.com) updated to include Superpages
'To Do List (with Local.com)'
https://na13.salesforce.com/00Oa0000008n4P1

-- New admin report created for assigning Superpages tasks 
'Add New Superpages Tasks'
https://na13.salesforce.com/00Oa0000008nLo5

--Existing workflow to populate Ready to review date 48 hours after status is flipped to submitted

--New report created for reviewing Superpages tasks ready to review 
'Global: Superpages Ready to Review'
https://na13.salesforce.com/00Oa0000008nLoA
