### ISSUE TITLE
SEO Cancellations on SF Homepage

### ISSUE THREAD

**Issue by officite** [ahuensch/officite#34]
I want to give the search specialists visibility into cancellations on the homepage of SF. Similar to the  "health checks" dashboard that currently exists for them. Ask Lindsey if you have questions.

**Comment by ahuensch** [comment]
Hi Lindsey - 

Fred opened a case requesting Search Specialists have cancellation visibility on the home page.  Home page page-layouts max out at three dashboard components.  

We currently have Health Checks, Quarterly Updates, Ad-words Checks Completed this week.

Do you want to replace or restructure them? 

Maybe personalize them to the specialist (i.e. my completed tasks this week, my tasks due this week, my cancellations this week)?

Let me know what you think. 

Cheers, 
Anna

**Comment by ahuensch** [comment]
Revised - Home Page: Search Specialist
https://na13.salesforce.com/01Za0000000fggt
