### ISSUE TITLE
Turn off notifications to ahuensch@officite.com for 'SFDC Job - Seo Action Task (seo_action_data__c) record creation - Hourly'

### ISSUE THREAD

**Issue by officite** [ahuensch/officite#36]
Anna - I get all of your and Jim's old emails and am getting a ton with the subject line:  7 SFDC Job - Seo Action Task (seo_action_data__c) record creation - Hourly

**Comment by officite** [comment]
I tried to filter them in Outlook but for some reason they keep popping up.

**Comment by ahuensch** [comment]
I can imagine! Those run every 15 minutes  from each layer of Salesforce (i.e. Production / Staging / Sandbox).  Those are system alerts we have rick put in place to ensure there isn't any failure for scheduled jobs/triggers.  From memory I think there is a custom setting where I can toggle those off for my email, if not we can reach out to Rick.

**Comment by ahuensch** [comment]
requested via Salesforce Admin Queue for Rick to update the schedule apex job
