### ISSUE TITLE
Update Sredl's permissions to change ownership of customer accounts

### ISSUE THREAD

**Issue by officite** [ahuensch/officite#37]
How do I get permissions so I can make this change moving forward?  Thanks!

Thomas Sredl
9:47 AM (10 minutes ago)

to me, Gregg 
Fred can you put this in Gregg McCampbell's name today so he can enter an order

Thanks
Tom

Tom Sredl  | Officite | Vice President, Sales
3010 Highland Parkway, Ste. 625, Downers Grove, IL 60515
t 630.230.2314 | f 630.230.2301 | m 224.315.7781

---------- Forwarded message ----------
From: Gregg McCampbell <gmccampbell@officite.com>
Date: Thu, Jun 25, 2015 at 9:30 AM
Subject: Re: https://na13.salesforce.com/001a000001Im5zX?srPos=1&srKp=001
To: Thomas Sredl <tsredl@officite.com>

Tom, 

 I have the ok to place the SEO order for Dr. Arroyo, but the account is still not in my name. 

Sydon Arroyo, DDS

Gregg McCampbell | Officite | Web Presence Advisor 
3010 Highland Parkway | Suite 625 | Downers Grove, IL 60515
Direct 630.230.2381| Fax 630.230.2301
www.officite.com

**Comment by ahuensch** [comment]
After researching the permission for updating account owner on customer accounts.  It appears to be controlled in an Apex Trigger trgAccountLockDown. Currently only Accounting, System Admins, & API Users are exempt.  Opening a case for Rick to request that Officite Sales Manager User profile be added the list of exceptions.
