### ISSUE TITLE
Incorrect blog # sequencing for assets receiving more than 1 blog per month

### ISSUE THREAD

**Issue by officite** [ahuensch/officite#46]
Brad discovered that for blog programs that receive two blogs a month, the numbering for which blog the client should receive is off. 

For example, if client received blog #1 at beginning of month, they will receive blog #1 at end of month again. Then at start of month two, SF will say the client should receive blog #2, even though it should be blog #3.

OR

For beginning of month, they will receive blog #1 and at end of month they will receive blog #2. Then for the next month, SF will say client should receive blog #2 again, even though it should be blog #3.

**Comment by officite** [comment]
Also, Brad manually adds the number 1 for "blog post number" on the first action task for the blog post. Is there a way for the asset to automatically start with number 1 moving forward? I know we had him manually add it previously since we had clients who had been in the program many months, but now that we are caught up, all new blog management clients will always start at blog #1. See lindsey with questions.

**Comment by ahuensch** [comment]
There was a bug in how the max blog post # was being calculated.  It was only looking at the max of either the 1st or 15th of the month blog posts actions. 

This has been corrected by rolling up the max blog post # value from both 1st/15th of the month action to the blog asset.  Workflow rule 'Action Task: Blog Post Task Created' has been updated to source Asset__r.Max_Blog__c + 1
