### ISSUE TITLE
Default program start date to rate start date for Offcite blog clients

### ISSUE THREAD

**Issue by officite** [ahuensch/officite#47]
Can the "program start date" on the asset automatically pull from the "start date" already provided on the asset level? Brad manually has to add the "program start date" currently, but it is always the same as the start date provided on the blog post service - 2 per month asset. 

Additionally, can the first action task to add a blog post coincide with the start date? Currently if Brad adds a start date of 7/1/2015, an action task to add the first blog post won't be generated until 8/1/2015, but we need to post a blog on the start date of 7/1/2015. See lindsey with questions.

**Comment by ahuensch** [comment]
Blog programs will automatically start at 8:00pm every day based on the first rate start date associated with the blog asset.
