### ISSUE TITLE
List of Clients Without Responsive Designs

### ISSUE THREAD

**Issue by officite** [ahuensch/officite#57]
Anna - can you pull a list of clients that don't have a responsive design.  In the report I would like to see the client name, contact information and date they signed up with Officite.  Thanks!

**Comment by ahuensch** [comment]
Here you go - 

Accounts without Responsive Designs
https://na13.salesforce.com/00Oa0000008nNJn

**Reminder** Salesforce data about responsive vs. standard templates is only as accurate as we are good about manually updating as we make changes in provisioning.  I recommend for a greater degree of accuracy running this report from provisioning. 

If we want to do another sync between Salesforce-Provisioning, you can provide: website id, template #, template name, color #, market, responsive yes/no, and I can globally update website records in Salesforce
