### ISSUE TITLE
Exclude facebook and live chat related cases from dashboard counts

### ISSUE THREAD

**Issue by officite** [ahuensch/officite#66]

**Comment by officite** [comment]
Hi Anna,

We have noticed a large number of cases opened on a daily basis.  Upon further investigation, I've learned that we are counting live chat history and likes, comments, etc. from our clients FB pages.

Can we filter this out of our numbers?

Thanks!

Patti

**Comment by ahuensch** [comment]
Updated the following reports with the additional criteria below: 
Subject DOES NOT CONTAIN 'Live Chat'
Web Email NOT EQUAL TO noreply@facebookmail.com
Type NOT EQUAL TO 'Junk Mail'

CS Cases Closed: Yesterday
CS: Cases Opened Yesterday
CS: Cases Closed This Week
CS: Cases Opened This Week
