### ISSUE TITLE
Add the ability to queue up cancellations from the Accounting Queue

### ISSUE THREAD

**Issue by officite** [ahuensch/officite#69]
Accounting does not want cancellations to sit in their accounting queue when there is a designated due date a few days/weeks out.  Is there an option to add a designated due date so that it can be closed out, but not officially until the due date.

**Comment by ahuensch** [comment]
In regards to scheduling cancellations....

I've added a new asset status called 'Scheduled Cancellation'.   When you select the asset status scheduled cancellation, you can still select an asset cancellation reason, provide asset cancellation notes, but the rates and cases will not be generated right then.  Instead, on the cancel date indicated on the asset, a time-dependent workflow rule will fire flipping the asset status to cancelled causing the rate to cancel and cancellation cases to be generated. 

You can immediately start to schedule cancellations with this method by manually updating assets (or mass updating in tool and then going back and updating cancel date individually); however, you won't  be able to completely execute the process with the mass update tool yet.  We are waiting on an enhancement request from Rick to update the tool to collect the desired cancellation date. He has estimated 4 hours to complete. 

Let me know if you have any question, concerns, etc. 

Best regards,
Anna
