### ISSUE TITLE
Surface Service Agreement on Cases / Sync Template on Quote with Template on Website Hosting Asset

### ISSUE THREAD

**Issue by officite** [ahuensch/officite#71]

**Comment by officite** [comment]
HI Anna,

Is it possible to embed the SA agreement within the Design upgrade case?  This help on a few levels - if the SA was actually sent in, we will be able to determine if this was approved by the client or WPA.  Also, when a client submits their selected design choice, Therese (now me) will go into the appropriate opportunity, then service agreement and add the design choice + dropdown selected by origin = client.  Is there a way for this to carry over to the hosting asset automatically?

Thanks,

Patti

**Comment by ahuensch** [comment]
Added flow to stamp related service agreement on the case under the additional information section moving forward for easy access to updated template selection / selected by.

Updated existing open cases titled 'Design Choice Upgrade' with Service Agreement as well.

**Comment by ahuensch** [comment]
**Please note the following only works on orders for NEW WEBSITES**

Added flow to sync template selection on service agreement with the template selection on on the website hosting asset created from that same service agreement. 

Consequently, on a new website order, if you update the template selection, the template on the corresponding website hosting asset will update as well. 

I will continue to mental-jungle-gym how we can sync the website hosting asset template selection with the quote of an upgrade or template change.  But this is difficult as it is hard to navigate the data model without code to identify the proper website hosting asset.
