### ISSUE TITLE
SEO Cancellations - SF Data

### ISSUE THREAD

**Issue by officite** [ahuensch/officite#82]
I'm trying to figure out what the past way to record saved cancellations as well as additional data for canceled programs. Below is what I'm thinking I need for both:

For saved clients:
-search specialist that saved it and logged notes (maybe we can just add another "method of contact" reason in SF for "saved SEO client"?). That way I can pull a report every week to see who saved it and the notes to validate the save.

Cancelled SEO clients:
-Cancellation reason
-Was there a follow up call to save client? Which search specialist spoke to them?
-How was the client's website ranking at time of cancellation?

Let me know your thoughts Anna! I wasn't sure what would be easiest in SF - Thanks, Lindsey.

**Comment by ahuensch** [comment]
Added Purpose of Contact value 'Product Retention' 

Created report for viewing: 
SEO Retention Activities - This Month
https://na13.salesforce.com/00Oa0000008nP7z

Tell me more about what you want to see on the SEO cancellations report?  Where would we pull ranking information at the time of cancellation?
