### ISSUE TITLE
Visibility on neglected SEO campaigns

### ISSUE THREAD

**Issue by officite** [ahuensch/officite#83]
Anna - is there a way to pull a report that can show me the most recent activity for accounts that have the Target SEO Maintenance asset?

**Comment by ahuensch** [comment]
What do you mean by activity?  Like any activity by any employee logged on
that account? or like the last completed seo related task?

On Mon, Jul 13, 2015 at 8:15 PM, officite <notifications@github.com> wrote:

> Anna - is there a way to pull a report that can show me the most recent
> activity for accounts that have the Target SEO Maintenance asset?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ahuensch/officite/issues/83>.
>



-- 
*Anna Huensch*
1546 North LaSalle, Chicago, IL 60610
t *630.639.1960*

**Comment by ahuensch** [comment]
What are you looking to do with the report / data?


On Mon, Jul 13, 2015 at 8:17 PM, Anna Huensch <anna.huensch@gmail.com>
wrote:

> What do you mean by activity?  Like any activity by any employee logged on
> that account? or like the last completed seo related task?
>
> On Mon, Jul 13, 2015 at 8:15 PM, officite <notifications@github.com>
> wrote:
>
>> Anna - is there a way to pull a report that can show me the most recent
>> activity for accounts that have the Target SEO Maintenance asset?
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/ahuensch/officite/issues/83>.
>>
>
>
>
> --
> *Anna Huensch*
> 1546 North LaSalle, Chicago, IL 60610
> t *630.639.1960*
>



-- 
*Anna Huensch*
1546 North LaSalle, Chicago, IL 60610
t *630.639.1960*

**Comment by officite** [comment]
I found an account today hadn't been touched in several months and I had to issue a credit.  We have the bandwidth now where this shouldn't happen.  I wanted to do an audit to see if there were any other SEO maintenance accounts without activity that the search specialist may have missed.

**Comment by ahuensch** [comment]
The following report shows 25 SEO assets that haven't been started.

Active SEO Assets without Program Start Date
https://na13.salesforce.com/00Oa0000007vjGH


On Mon, Jul 13, 2015 at 8:53 PM, officite <notifications@github.com> wrote:

> I found an account today hadn't been touched in several months and I had
> to issue a credit. We have the bandwidth now where this shouldn't happen. I
> wanted to do an audit to see if there were any other SEO maintenance
> accounts without activity that the search specialist may have missed.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ahuensch/officite/issues/83#issuecomment-121109674>.
>



-- 
*Anna Huensch*
1546 North LaSalle, Chicago, IL 60610
t *630.639.1960*

**Comment by officite** [comment]
Anna - when I run the report I get: 
Data Not Available
The data you were trying to access could not be found. It may be due to another user deleting the data or a system error. If you know the data is not deleted but cannot access it, please look at our support page.

**Comment by ahuensch** [comment]
Try again.

Also I've added -

Action SEO without recent Check
https://na13.salesforce.com/00Oa0000008nP84



On Mon, Jul 13, 2015 at 8:59 PM, officite <notifications@github.com> wrote:

> Anna - when I run the report I get:
> Data Not Available
> The data you were trying to access could not be found. It may be due to
> another user deleting the data or a system error. If you know the data is
> not deleted but cannot access it, please look at our support page.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ahuensch/officite/issues/83#issuecomment-121110274>.
>



-- 
*Anna Huensch*
1546 North LaSalle, Chicago, IL 60610
t *630.639.1960*

**Comment by ahuensch** [comment]
FYI - I found a bug in the calculation of last monthly health check (now fixed).  Please note the contents of the report have been revised.
