### ISSUE TITLE
Update case status to 'Client Responded' when an email reply is received

### ISSUE THREAD

**Issue by officite** [ahuensch/officite#86]
When a rep is communicating with a client inside of a case they have been changing the status to Awaiting Client Response.  The issue is that when the client responds, there is no trigger in the case that alerts the rep that a response has been received (other than the email they received).  Is it possible to have the status of the case updated to Client Responded, every time a customer responds to an email chain?  I can then run reporting on all cases that have this status to ensure that we are responding in a timely manner.

**Comment by ahuensch** [comment]
Inbound email messages related to open cases will flip the status detail to 'Client Responded'

New report setup to ensure visibility: 
Open Cases - Client Response Received
https://na13.salesforce.com/00Oa0000008nPOC
