### ISSUE TITLE
Modify My Open SEO Maintenance Tasks report

### ISSUE THREAD

**Issue by officite** [ahuensch/officite#90]
Can we add the below fields for each search specialist's monthly report displaying the below info:

-date of last health check
-ranking status (field with drop down menu for search specialist to pick whether the last health check was "good" or "bad")

**Comment by ahuensch** [comment]
Can you provide the link to the monthly report you would like updated?

ranking status - is this a new field you would like added? Is this
something to be collected on the action task moving forward?

On Wed, Jul 15, 2015 at 1:47 PM, officite <notifications@github.com> wrote:

> Can we add the below fields for each search specialist's monthly report
> displaying the below info:
>
> -date of last health check
> -ranking status (field with drop down menu for search specialist to pick
> whether the last health check was "good" or "bad")
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ahuensch/officite/issues/90>.
>



-- 
*Anna Huensch*
1546 North LaSalle, Chicago, IL 60610
t *630.639.1960*

**Comment by ahuensch** [comment]
Hi Anna,

Heres the report to update: https://na13.salesforce.com/00Oa0000007xsUi

In regards to "ranking status," this is a new field to add to the report. Ideally it would be housed on each action item for monthly health checks. So when someone is completing a health check, they can toggle whether the client is ranking good or bad.  

In addition to that, if the "last ranking status" can be displayed on each search specialist's report that would be helpful as well.

Let me know if you need any of that clarified.

Thanks,

Lindsey

**Comment by ahuensch** [comment]
Updated report to display Last Monthly Health Check

**Comment by ahuensch** [comment]
Added Ranking Status as picklist on monthly health check action tasks. 
When a task is mark completed, the ranking status is stamped on the asset marking it with the ranking status of the action task to last be marked completed. 
Added validation prevent search specialists from marking a health check completed without a ranking status
Added validation preventing a search specialist from updating the ranking status on a previously completed action task
Updated the My SEO Maintenance Tasks report to display the last ranking status as well as last monthly health check values
