### ISSUE TITLE
Report of Cancelled Accounts

### ISSUE THREAD

**Issue by officite** [ahuensch/officite#99]
We are starting a winback campaign for cancelled accounts.  Is there a way to get a report with their previous spend, cancellation reason (to the extent we have it), name, address, phone #, email.

**Comment by ahuensch** [comment]
Below is a link to a report summarizing account level information on cancelled accounts in our org: 

Winback Campaign - Cancelled Accounts
https://na13.salesforce.com/00Oa0000008nQ0p

We don't currently capture previous spend at the time of cancellation.  Total average recurring monthly on account only displays what is active at this moment in time.  Once accounts are cancelled values return to $0.00. 

Now if that's something we're interested in starting to collect moving forward I would be happy to assist - but we would have to leverage Salesforce snapshots or something like that. 

Additionally, it was unclear in your request the purpose of this report.  If you need something specifically for targeting contacts via ExactTarget let me know and we can change the report type to a standard one and include individual contact information.
